#ifndef PROTOCOL_OPCODES_H
#define PROTOCOL_OPCODES_H

typedef enum
{
    // Genericos
    OP_MENSAJE = 0,
    OP_PAQUETE,
    OP_OK = 10,
    OP_FAIL = 11,

    // Handshakes
    OP_HANDSHAKE_KERNEL = 100,
    OP_HANDSHAKE_CPU,
    OP_HANDSHAKE_MEMORIA,
    OP_HANDSHAKE_IO,

    // Kernel <-> CPU
    OP_PROCESO_EXEC = 200,
    OP_INTERRUPCION_CPU,
    OP_FIN_DE_QUANTUM,
    OP_FIN_DE_PROCESO,
    OP_BLOQUEO_IO,
    OP_WAIT_RECURSO,
    OP_SIGNAL_RECURSO,
    OP_ERROR_MEMORIA,
    OP_DESALOJO,
    OP_SEGFAULT,

    // Kernel/CPU <-> Memoria
    OP_INIT_PROCESO = 300,
    OP_FIN_PROCESO,
    OP_ACCESO_TABLA,
    OP_LEER_MEMORIA,
    OP_ESCRIBIR_MEMORIA,
    OP_FETCH_INSTRUCCION,
    OP_AJUSTAR_TAMANIO,
    OP_RESPUESTA_TRADUCCION,
    OP_RESPUESTA_INSTRUCCION,
    OP_RESPUESTA_LECTURA,
    OP_RESPUESTA_ESCRITURA,

    // IO
    OP_IO_STDIN = 400,
    OP_IO_STDOUT,
    OP_IO_FS_CREATE,
    OP_IO_FS_DELETE,
    OP_IO_FS_TRUNCATE,
    OP_IO_FS_WRITE,
    OP_IO_FS_READ,
    OP_IO_GENERIC_SLEEP,
    OP_IO_FIN = 450

} op_code;

#endif