#ifndef PROTOCOL_OPCODES_H
#define PROTOCOL_OPCODES_H

typedef enum
{
    // Genericos
    OP_FAIL = 0,
    OP_OK,
    OP_MENSAJE,
    OP_PAQUETE,
    OP_RESPUESTA_GENERICA,

    // Handshake
    OP_HANDSHAKE,
    OP_HANDSHAKE_IO,

    // Kernel <-> CPU
    OP_PROCESO_EXEC = 200,
    OP_INTERRUPCION_CPU,
    OP_FIN_DE_QUANTUM,
    OP_CPU_FIN_PROCESO,
    OP_DESALOJO,
    OP_SEGFAULT,

    // Kernel <-> Memoria
    OP_MEM_INIT_PROCESO = 300,
    OP_MEM_FIN_PROCESO,
    OP_MEM_TRADUCIR_PAGINA,
    OP_MEM_LEER,
    OP_MEM_ESCRIBIR,
    OP_MEM_FETCH_INSTRUCCION,
    OP_MEM_AJUSTAR_TAMANIO,
    OP_MEM_RESP_TRADUCCION,
    OP_MEM_RESP_INSTRUCCION,
    OP_MEM_RESP_LECTURA,
    OP_MEM_RESP_ESCRITURA,

    // IO
    OP_IO_SLEEP = 400,
    OP_IO_FS_CREATE,
    OP_IO_FS_DELETE,
    OP_IO_FS_TRUNCATE,
    OP_IO_FS_WRITE,
    OP_IO_FS_READ,
    OP_IO_FIN_OPERACION,
    OP_SIGNAL_RECURSO,
    OP_WAIT_RECURSO,
    OP_BLOQUEO_IO,
    OP_IO_STDIN_READ,
    OP_IO_STDOUT_WRITE,

    // Consola <-> Kernel
    OP_CONSOLA_RUN = 500,
    OP_CONSOLA_KILL,
    OP_CONSOLA_PS,
    OP_CONSOLA_ALGORITMO,
    OP_CONSOLA_START,
    OP_CONSOLA_PAUSE,
    OP_CONSOLA_DESALOJAR,
    OP_CONSOLA_PS_RESP,
    OP_CONSOLA_EXIT

} op_code;

#endif